export const MARVEL_CHARACTER_BY_NAME = '[MARVEL] MARVEL_CHARACTER_BY_NAME';
export const MARVEL_COMICS_BY_LIMIT   = '[MARVEL] MARVEL_COMICS_BY_LIMIT';
export const MARVEL_COMICS_BY_CHARACTERS = '[MARVEL] MARVEL_COMICS_BY_CHARACTERS';
